//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComunityContactsForCountry
    {
        public int CountryCode { get; set; }
        public int ComunityCode { get; set; }
        public string NumbreOfResidents { get; set; }
    
        public virtual Comunity Comunity { get; set; }
        public virtual Country Country { get; set; }
    }
}
