//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comunity
    {
        public int ComunityCode { get; set; }
        public string ComunityName { get; set; }
        public int CityCode { get; set; }
        public int SectorCode { get; set; }
        public int CostoCode { get; set; }
        public bool anciano { get; set; }
        public string About { get; set; }
        public int RepresentanteCode { get; set; }
    
        public virtual NewCity NewCity { get; set; }
        public virtual NewCosto NewCosto { get; set; }
        public virtual Representante Representante { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
