//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comunity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comunity()
        {
            this.ComunityContacts = new HashSet<ComunityContact>();
            this.ComunityContactsForCountries = new HashSet<ComunityContactsForCountry>();
        }
    
        public int ComunityCode { get; set; }
        public string ComunityName { get; set; }
        public int CityCode { get; set; }
        public string NeighborhoodName { get; set; }
        public string SinagogueName { get; set; }
        public string Size { get; set; }
        public int SectorCode { get; set; }
        public string PercentageOfPeople { get; set; }
        public string Workers { get; set; }
        public string MinAptPrice { get; set; }
        public string MaxAptPrice { get; set; }
    
        public virtual City City { get; set; }
        public virtual Sector Sector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComunityContact> ComunityContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComunityContactsForCountry> ComunityContactsForCountries { get; set; }
    }
}
