//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComunityContact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComunityContact()
        {
            this.Recommendations = new HashSet<Recommendation>();
        }
    
        public int ContactCode { get; set; }
        public int ComunityCode { get; set; }
        public int ProfessionCode { get; set; }
        public string ContactName { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string FamilyStatus { get; set; }
        public int SectorCode { get; set; }
        public string YearOfAlia { get; set; }
        public bool DoesSpeakSpanish { get; set; }
    
        public virtual Comunity Comunity { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual Sector Sector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recommendation> Recommendations { get; set; }
    }
}
