//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoveilEntities : DbContext
    {
        public MoveilEntities()
            : base("name=MoveilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comunity> Comunities { get; set; }
        public virtual DbSet<NewCity> NewCities { get; set; }
        public virtual DbSet<NewContact> NewContacts { get; set; }
        public virtual DbSet<NewCosto> NewCostoes { get; set; }
        public virtual DbSet<NewDistrito> NewDistritoes { get; set; }
        public virtual DbSet<Recommendation> Recommendations { get; set; }
        public virtual DbSet<Representante> Representantes { get; set; }
        public virtual DbSet<Sector> Sectors { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
