//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoveilEntities : DbContext
    {
        public MoveilEntities()
            : base("name=MoveilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Comunity> Comunities { get; set; }
        public virtual DbSet<ComunityContact> ComunityContacts { get; set; }
        public virtual DbSet<ComunityContactsForCountry> ComunityContactsForCountries { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<PlacesOfStudy> PlacesOfStudies { get; set; }
        public virtual DbSet<Profession> Professions { get; set; }
        public virtual DbSet<ProfessionsForPlaceToStudy> ProfessionsForPlaceToStudies { get; set; }
        public virtual DbSet<Recommendation> Recommendations { get; set; }
        public virtual DbSet<Sector> Sectors { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
