//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewCity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewCity()
        {
            this.Comunities = new HashSet<Comunity>();
            this.NewContacts = new HashSet<NewContact>();
        }
    
        public int CityCode { get; set; }
        public string CityName { get; set; }
        public int DistritoCode { get; set; }
        public string Poblacion { get; set; }
        public string AlquilerCentro { get; set; }
        public string AlquilerAfueras { get; set; }
        public string SalarioMinimo { get; set; }
        public string AboutCity { get; set; }
        public Nullable<int> NewPoblacion { get; set; }
        public Nullable<int> NewApt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comunity> Comunities { get; set; }
        public virtual NewDistrito NewDistrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewContact> NewContacts { get; set; }
    }
}
