//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendation
    {
        public int RecommendationCode { get; set; }
        public int ContactCode { get; set; }
        public string FreeDescription { get; set; }
    
        public virtual ComunityContact ComunityContact { get; set; }
    }
}
